#!/bin/sh
# Create a symbolic link to this in the .git/hooks directory

if [ $(git diff HEAD@{1} HEAD --name-only | grep -E '_normalize.scss' -c) -ne 0 ]; then
  echo "_normalize.scss changed, compiling"
  if type "sass" > /dev/null 2>&1; then
    sass --scss -lC ./_normalize.scss > ./normalize.css;
  else
    cat $theme_path/style.scss | ssh demo \
      "sass --scss --no-cache --style compressed" \
      > ./normalize.css
  fi
fi
